/* eslint-disable max-len */
import React, {useCallback, useEffect, useState} from "react";

import clpFfiJsModuleInit from "clp-ffi-js";
import {DalAstGenerator} from "dal-ast-js";
import {Code, Eye, Floppy, Pencil, Play, Trash} from "react-bootstrap-icons";
import {useDispatch} from "react-redux";
import {useModalManager} from "ui-layout-manager-dev";

import {useDalEngine} from "../../Providers/GlobalProviders";
import {useServer} from "../../Providers/GlobalProviders";
import {incrementCounter, setStatusMsg} from "../../Store/appSlice";
import {deleteTraceThunk} from "../../Store/appThunk";
import {useHasEntryPoint, useWorkbenchRedux} from "../../Store/useAppSelection";
import {useTraces} from "../../Store/useAppSelection";
import {useActiveTab} from "../../Store/useAppSelection";
import {AddTraceName} from "../Modals/AddTraceName";
import {ShowTraceLog} from "../Modals/ShowTraceLog";

import "./ImplementationToolbar.scss";

ImplementationToolbar.propTypes = {
};

/**
 * Implementation Tool Bar component.
 * @return {JSX.Element}
 */
export function ImplementationToolbar () {
    const dispatch = useDispatch();
    const {openModal} = useModalManager();
    const {engine} = useDalEngine();
    const {sendMessage} = useServer();
    const hasEntryPoint = useHasEntryPoint();
    const traces = useTraces();
    const [selectedTrace, setSelectedTrace] = useState(null);
    const [selectedVerbosity, setSelectedVerbosity] = useState("minimal");
    const activeTab = useActiveTab();
    const {workbench} = useWorkbenchRedux();

    const [invariants, setInvariants] = useState([]);
    const [selectedInvariant, setSelectedInvariant] = useState();

    const saveFile = useCallback(() => {
        if (workbench && activeTab) {
            const file = workbench.getFileUsingUid(activeTab);
            sendMessage({
                type: "save_file",
                data: file,
            });
            dispatch(setStatusMsg(`Saving file ${file.name}`));
        }
    }, [workbench, activeTab, dispatch]);

    useEffect(() => {
        console.log("Active Tab:", activeTab);
    }, [activeTab]);

    useEffect(() => {
        synthesizeDesign();
    }, []);

    const evaluateInvariant = useCallback(() => {
        if (workbench && selectedInvariant && "validator" in workbench) {
            workbench.validator.testInvariant(selectedInvariant);
        }
    }, [workbench, selectedInvariant]);

    const openTraceInEditor = useCallback(async (e) => {
        e.stopPropagation();
        e.preventDefault();
        if (!selectedTrace) {
            return;
        }

        const t = Object.values(traces).find((t) => t.uid === selectedTrace);
        if (!t) return;
        const traceData = t?.trace;

        // TODO: This should be in a worker, but I'm doing it here for now.
        const Module = await clpFfiJsModuleInit();
        const decoder = new Module.ClpStreamReader(traceData, {
            timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
            logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
        );
        const log = decoder.decodeRange(0, decoder.deserializeStream(), false);
        const logContent = log.map((entry) => {
            return JSON.stringify(JSON.parse(entry[0])["user-generated"], null, 2);
        }).join("\n");

        openModal({
            title: "Selected Trace Log",
            args: {
                "trace": logContent,
            },
            render: ({close, args}) => {
                return <ShowTraceLog close={close} args={args} />;
            },
        });
    }, [selectedTrace, traces]);

    const runDesign = useCallback(() => {
        if (sendMessage && workbench) {
            const cmd = workbench.getRunCommand();
            if (cmd) {
                sendMessage({
                    type: "terminal_run_entry_point",
                    payload: {
                        entryPoint: cmd,
                        selectedTrace: null,
                    },
                });
            } else {
                const failureMsg = "Failed to run design. Please ensure design has been synthesized into implementation.";
                sendMessage({
                    type: "terminal_run_entry_point",
                    payload: {
                        data: `echo ${failureMsg}`,
                        selectedTrace: null,
                    },
                });
            }
        }
    }, [sendMessage, workbench, selectedTrace]);


    const synthesizeDesign = useCallback(() => {
        // Load the entry point from metadata file.
        let entryPoint;
        for (const file of workbench.getFiles()) {
            if (file.name === "metadata.json") {
                entryPoint = JSON.parse(file.content)?.entryPoint;
                break;
            }
        }
        if (!entryPoint) {
            console.error("No entry point provided in metadata.json file");
        }
        // Get the AST and synthesize
        if (entryPoint && entryPoint.endsWith(".dal")) {
            for (const file of workbench.getFiles()) {
                if (file.name === entryPoint) {
                    const content = file.content;
                    const ast = new DalAstGenerator().run(content);
                    workbench.saveAst(ast);
                    console.log(ast);
                    sendMessage({
                        type: "synthesize_design",
                        payload: {
                            ast: workbench.ast,
                            verbosity: selectedVerbosity,
                        },
                    });
                    break;
                }
            }
            if (workbench && "validator" in workbench && "invariants" in workbench.validator) {
                setInvariants(workbench?.validator?.invariants);
                if (workbench.validator.invariants.length > 0) {
                    setSelectedInvariant(workbench.validator.invariants[0].name);
                }
            }
            dispatch(incrementCounter());
        }
    }, [workbench, dispatch, selectedVerbosity]);


    const deleteTrace = (e) => {
        e.stopPropagation();
        if (selectedTrace) {
            dispatch(deleteTraceThunk(selectedTrace));
        } else {
            console.warn("Trace does not have a valid UID:", selectedTrace);
        }
    };

    const setTraceName = useCallback(() => {
        if (selectedTrace) {
            openModal({
                title: "Set Trace Name",
                args: {
                    trace: selectedTrace,
                },
                render: ({close, args}) => {
                    return <AddTraceName close={close} args={args} />;
                },
            });
        }
    }, [selectedTrace, traces, openModal]);

    return (
        <div className="mainToolBar">
            <div className="mainToolBarLeft">
            </div>
            <div className="mainToolBarRight">
                {/* <span className="mainToolBarLabel">Environment:</span> */}
                <span className="mainToolBarSelect" >
                    <select
                        value={selectedInvariant}
                        onChange={(e) => setSelectedInvariant(e.target.value)}>
                        <option key={"none"} value={null}>None</option>
                        {
                            invariants && Object.values(invariants).map((invariant) => (
                                <option key={invariant.name} value={invariant.name}>{
                                    (invariant?.name )
                                }</option>
                            ))
                        }
                    </select>
                </span>
                <span className="mainToolBarButton" onClick={evaluateInvariant}>
                    <Play
                        size={20}
                        className="mainToolBarButton"
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span >Test Invariant</span>
                </span>
                <span className="debuggingToolBarButton"
                    onClick={setTraceName}
                    style={{"padding": "3px"}}
                    title="Set Trace Name">
                    <Pencil size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                </span>
                <span className="debuggingToolBarButton"
                    onClick={openTraceInEditor}
                    style={{"padding": "3px 0"}}
                    title="View Raw Trace">
                    <Eye
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                </span>
                <span className="debuggingToolBarButton"
                    onClick={deleteTrace}
                    style={{"padding": "3px 0"}}
                    title="Delete Trace">
                    <Trash
                        size={14}
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                </span>
                <span className="mainToolBarSelect" >
                    <select
                        value={selectedVerbosity}
                        onChange={(e) => setSelectedVerbosity(e.target.value)}>
                        <option key={"minimal"} value={"minimal"}>Minimal Logging</option>
                        <option key={"verbose"} value={"verbose"}>Verbose Logging</option>
                    </select>
                </span>
                <span className="mainToolBarButton" onClick={synthesizeDesign}>
                    <Code
                        size={15}
                        className="mainToolBarButton"
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span >Synthesize</span>
                </span>
                <span className="mainToolBarButton" onClick={runDesign}>
                    <Play
                        size={20}
                        className="mainToolBarButton"
                        style={{"color": "white", "cursor": "pointer", "padding": "0 5px"}}/>
                    <span >Run</span>
                </span>

                <span className="mainToolBarButton" onClick={saveFile}>
                    <Floppy
                        size={14}
                        className="mainToolBarButton"
                        style={{"color": "white", "cursor": "pointer", "padding": "0 0 0 7px"}}/>
                </span>
            </div>
        </div>
    );
}
