export const selectCounter = (state) => state.app.counter;
export const selectActiveTab = (state) => state.app.activeTab;
export const selectStatusMsg = (state) => state.app.statusMsg;
export const selectLastSaved = (state) => state.app.lastSaved;
export const selectAppMode = (state) => state.app.appMode;
export const selectDesignLoaded = (state) => state.app.designLoaded;
export const selectHasEntryPoint = (state) => state.app.hasEntryPoint;
export const selectSelectedTraceId = (state) => state.app.selectedTraceId;
export const selectSelectedBehavior = (state) => state.app.selectedBehavior;
